######################################################################
# Automatically generated by qmake (2.01a) ?? 23. ??? 18:15:48 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += chartSetup.h cmnExtInclude.h tvaChart.h
SOURCES += chartSetup.cpp tvaChart.cpp
