######################################################################
# Automatically generated by qmake (2.01a) ?? 15. ??? 11:41:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += chartSetup.h cmnExtInclude.h tvaChart.h
SOURCES += chartSetup.cpp tvaChart.cpp
