######################################################################
# Automatically generated by qmake (2.01a) ?? 23. ??? 18:16:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cmnExtInclude.h tvaMatrix.h ../tva_interval.h ../primary.h
SOURCES += tvaMatrix.cpp ../tva_interval.cpp
